# Generated by Django 5.0.2 on 2025-04-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KwentasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('file_name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
