# Generated by Django 5.0.2 on 2025-04-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KwentasApp', '0002_uploadedfiledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiledata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfiledata',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
