# Generated by Django 5.0.2 on 2025-04-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KwentasApp', '0003_uploadedfiledata_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiledata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
