# Generated by Django 5.0.2 on 2025-05-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KwentasApp', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiledata',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
